# Generated by Django 5.2.8 on 2025-12-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_album_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='slug',
            field=models.SlugField(default=None, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='musica'),
        ),
    ]
