# Generated by Django 5.2.8 on 2025-12-10 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_cancion_slug_alter_album_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='musica.artista'),
        ),
        migrations.AlterField(
            model_name='album',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='musica'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='musica.album'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
