# Generated by Django 5.2.8 on 2025-12-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0004_alter_album_artista_alter_album_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
