# Generated by Django 5.2.8 on 2025-12-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0005_cancion_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
