# Generated by Django 5.2.8 on 2025-12-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0006_artista_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', unique=True),
        ),
    ]
