# Generated by Django 5.2.8 on 2025-12-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0008_alter_artista_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
