# Generated by Django 6.0 on 2026-01-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0009_album_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='slug',
        ),
    ]
