# Generated by Django 6.0 on 2026-01-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0010_remove_cancion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
