# Generated by Django 6.0 on 2026-01-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0011_cancion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
