# Generated by Django 5.2.8 on 2025-11-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='imagen',
            field=models.ImageField(default='null', upload_to='album'),
        ),
    ]
