# Generated by Django 5.2.8 on 2025-12-10 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contenidoresenia_delete_contenido'),
        ('musica', '0004_alter_album_artista_alter_album_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoresenia',
            name='calificacion',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contenidoresenia',
            name='musica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenias', to='musica.cancion'),
        ),
    ]
