# Generated by Django 5.2.8 on 2025-12-12 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contenidoresenia_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidoresenia',
            name='calificacion',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
