# Generated by Django 5.2.8 on 2025-11-08 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoResenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musica.cancion')),
            ],
        ),
        migrations.DeleteModel(
            name='Contenido',
        ),
    ]
